---
- name: update apt packages
  become: true
  apt:
    update_cache: true

- name: upgrade apt packages
  become: true
  apt:
    upgrade: true

- name: remove dependencies that are no longer required
  become: true
  apt:
    autoremove: true

- name: install dependencies
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: true

- name: install pm2
  npm:
    name: pm2
    global: yes
    production: yes
    state: latest

- name: create web dir at root
  file:
    path: ~/web
    state: directory

- name: copy index.js file to web dir
  template:
    src: "files/index.js"
    dest: "~/web/index.js"

- name: start pm2 server
  shell: |
    pm2 start ~/web/index.js -f
